// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {option} from '../models';

export function AddServer(arg1:string,arg2:option.Outbound):Promise<void>;

export function GetAllServers():Promise<Array<any>>;

export function RemoveServer(arg1:string):Promise<void>;

export function RunServer():Promise<void>;
