// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1, arg2) {
  return window['go']['main']['App']['AddServer'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAllServers() {
  return window['go']['main']['App']['GetAllServers']();
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function RunServer(arg1) {
  return window['go']['main']['App']['RunServer'](arg1);
}
