// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllServers(arg1:string):Promise<Array<Array<number>>>;

export function Greet(arg1:string):Promise<string>;
